export type VicimById = {
  idDefendant: number;
  idPerson: number;
  idOfficer: number;
  name: string;
  lastName: string;
  idCounty: number;
  eMail: string;
  birthDate: string;
  idGender: number;
  idPersonType: number;
  idStatus: number;
  createdAt: string;
  idRole: number;
  phone: string;
  deviceId: number;
  idDeviceType: number;
  showalerts: false;
  userName: string;
  caseNumber: string;
};
