export type UserManage = {
  birthDate: string;
  caseNumber: string;
  createdAt: string;
  deviceId: number;
  eMail: string;
  idCounty: number;
  idDefendant: number;
  idDeviceType: number;
  idGender: number;
  idOfficer: number;
  idPerson: number;
  idPersonType: number;
  idRole: number;
  idStatus: number;
  lastName: string;
  name: string;
  role: string;
  sid: string;
  userName: string;
  // phone: string;
};
