export type DefendantInactive = {
  idDefendant: number;
  idPerson: number;
  idOfficer: number;
  name: string;
  lastName: string;
  idCounty: number;
  eMail: string;
  caseNumber: string;
  birthDate: string;
  idGender: number;
  sid: string;
  idPersonType: number;
  idStatus: number;
  createdAt: string;
  idRole: number;
  role: string;
  deviceId: number;
  idDeviceType: number;
  showalerts: boolean;
};
