export type DefendantById = {
  birthDate: string;
  caseNumber: string;
  createdAt: string;
  deviceId: number;
  eMail: string;
  idCounty: number;
  idDefendant: number;
  idDeviceType: number;
  idGender: number;
  idOfficer: number;
  idPerson: number;
  idPersonType: number;
  idRole: number;
  idStatus: number;
  lastName: string;
  name: string;
  notes: string;
  offense: string;
  officer: string;
  phone: string;
  showalerts: boolean;
  sid: string;
  userName: string;
};
